backend/config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get 'activities/:id/export', to: 'activities#export'
  get 'activities/:id/ppg_measures', to: 'activities#ppg_measures'
  get 'download_wearos_apk', to: 'welcome#download_wearos_apk'
  get 'download_android_apk', to: 'welcome#download_android_apk'
  resources :activities
  constraints Rodauth::Rails.authenticated do
    get '/dashboard/index', to: 'dashboard#activity_user'
    get '/dashboard', to: 'dashboard#activity_user'
    get '/dashboard/create_user' => 'dashboard#create_user', as: :dashboard_create_user
    get '/dashboard/create_user/search' => 'dashboard#search_user', as: :dashboard_search_user
    post '/dashboard/create_user', to: 'users#create'
    get '/dashboard/activity_user' => 'dashboard#activity_user', as: :dashboard_activity_user
    get '/dashboard/activity_user/search' => 'dashboard#search_user_activities', as: :dashboard_search_user_activity
    get '/dashboard/activity_user/:id' => 'dashboard#view_activities', as: :dashboard_view_activity
    get '/dashboard/activity_user/:id/:id_activity' => 'dashboard#activity_details', as: :dashboard_activity_details
    get '/dashboard/activity_user/:id/:id_activity/reprocess' => 'activities#reprocess', as: :activity_reprocess
    resources :ppg_measures
    resources :users
    resources :tags
  end

  get '/welcome/index'
  namespace :user do
    resource :private_api_keys, only: :update
  end

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        resources :users, only: [:index]
        get 'users/get_api_key', to: 'users#get_api_key'
        get 'users/password_recovery', to: 'users#post_password_recovery'
        resources :measures, only: [:index, :create, :show, :update, :destroy]
        resources :activities, only: [:index, :create, :show, :update, :destroy]
        resources :ppg_measures, only: [:index, :create, :show, :update, :destroy]
        resources :tags, only: [:index, :create, :show, :update, :destroy]
      end
    end
  end

end

backend/app/views/layouts/_dashboard.html.erb
<%= render "layouts/navbar" %>
<%= stylesheet_link_tag 'dashboard.css' %>

<script>$(document).ready(function() {
    feather.replace()
});</script>

<div class="container-fluid d-md-none">
  <nav class="tabbable">
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <% if current_page?(dashboard_create_user_path)%>
        <a class="nav-item nav-link active" id="nav-profile-tab" data-toggle="tab" href="<%= dashboard_create_user_url %>" role="tab" aria-controls="nav-profile" aria-selected="true"><span data-feather="users"></span> Usuarios</a>
      <% else %>
        <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="<%= dashboard_create_user_url %>" role="tab" aria-controls="nav-profile" aria-selected="false"><span data-feather="users"></span> Usuarios</a>
      <% end %>
      <% if current_page?(dashboard_activity_user_path)%>
        <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="<%= dashboard_activity_user_url %>" role="tab" aria-controls="nav-contact" aria-selected="true"><span data-feather="bar-chart-2"></span> Actividades</a>
      <% else %>
        <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="<%= dashboard_activity_user_url %>" role="tab" aria-controls="nav-contact" aria-selected="false"><span data-feather="bar-chart-2"></span> Actividades</a>
      <% end %>
    </div>
  </nav>
</div>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-none d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-5">
        <ul class="nav flex-column">
          <li class="nav-item">
            <% if current_page?(dashboard_create_user_path) %>
              <%= link_to dashboard_create_user_path, class: "nav-link active" do %>
                <span data-feather="users"></span>
                Usuarios
              <% end %>
            <% else %>
              <%= link_to dashboard_create_user_path, class: "nav-link" do %>
                <span data-feather="users"></span>
                Usuarios
              <% end %>
            <% end %>
          </li>
          <li class="nav-item">
            <% if request.url.include? 'activity_user' %>
              <%= link_to dashboard_activity_user_path, class: "nav-link active" do %>
                <span data-feather="bar-chart-2"></span>
                Actividades
              <% end %>
            <% else %>
              <%= link_to dashboard_activity_user_path, class: "nav-link" do %>
                <span data-feather="bar-chart-2"></span>
                Actividades
              <% end %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>

backend/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm sticky-top navbar-dark bg-dark flex-md-nowrap p-0 shadow">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_url %>">
      <%= image_tag ("logos/dibujo.svg"), class: "", width: 200%>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link <%= 'active' if current_page?(welcome_index_path) or current_page?(root_path)%>" aria-current="page" href="<%= root_url %>">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= 'active' if params[:controller] == 'dashboard'%>" aria-current="page" href="<%= dashboard_activity_user_url %>">Panel de control</a>
        </li>
      </ul>
      <div class="d-flex">
        <% if rodauth.logged_in? %>
          <%= link_to "Salir", rodauth.logout_path, method: :post, class: "btn btn-warning" %>
        <% else %>
          <%= link_to "Entrar", rodauth.login_path, class: "btn btn-outline-light me-2" %>
          <%= link_to "Registrarse", rodauth.create_account_path, class: "btn btn-warning" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<meta charset="utf-8"/>
<head>
  <title>TFG</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= favicon_link_tag asset_path('logos/favicon.png') %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"></script>

  <% if notice %>
    <script>
        $(function() {
          Swal.mixin({
              toast: true,
              position: 'bottom-end',
              showConfirmButton: false,
              timer: 3000,
              timerProgressBar: true,
              didOpen: (toast) => {
                  toast.addEventListener('mouseenter', Swal.stopTimer)
                  toast.addEventListener('mouseleave', Swal.resumeTimer)
              }
          }).fire({
              icon: 'info',
              title: '<%= notice %>'
          });
      });
  </script>
  <% end %>
  <% if alert %>
    <script>
        $(function() {
          Swal.mixin({
              toast: true,
              position: 'top-end',
              showConfirmButton: false,
              timer: 3000,
              timerProgressBar: true,
              didOpen: (toast) => {
                  toast.addEventListener('mouseenter', Swal.stopTimer)
                  toast.addEventListener('mouseleave', Swal.resumeTimer)
              }
          }).fire({
              icon: 'warning',
              title: '<%= alert %>'
          });
      });
  </script>
  <% end %>
</head>

<body class="<%= yield (:body_class) %>">
<%= yield %>
</body>
</html>