backend/config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get 'activities/:id/export', to: 'activities#export'
  get 'activities/:id/ppg_measures', to: 'activities#ppg_measures'
  get 'download_wearos_apk', to: 'welcome#download_wearos_apk'
  get 'download_android_apk', to: 'welcome#download_android_apk'
  resources :activities
  constraints Rodauth::Rails.authenticated do
    get '/dashboard/index', to: 'dashboard#activity_user'
    get '/dashboard', to: 'dashboard#activity_user'
    get '/dashboard/create_user' => 'dashboard#create_user', as: :dashboard_create_user
    get '/dashboard/create_user/search' => 'dashboard#search_user', as: :dashboard_search_user
    post '/dashboard/create_user', to: 'users#create'
    get '/dashboard/activity_user' => 'dashboard#activity_user', as: :dashboard_activity_user
    get '/dashboard/activity_user/search' => 'dashboard#search_user_activities', as: :dashboard_search_user_activity
    get '/dashboard/activity_user/:id' => 'dashboard#view_activities', as: :dashboard_view_activity
    get '/dashboard/activity_user/:id/:id_activity' => 'dashboard#activity_details', as: :dashboard_activity_details
    get '/dashboard/activity_user/:id/:id_activity/reprocess' => 'activities#reprocess', as: :activity_reprocess
    resources :ppg_measures
    resources :users
    resources :tags
  end

  get '/welcome/index'
  namespace :user do
    resource :private_api_keys, only: :update
  end

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        resources :users, only: [:index]
        get 'users/get_api_key', to: 'users#get_api_key'
        get 'users/password_recovery', to: 'users#post_password_recovery'
        resources :measures, only: [:index, :create, :show, :update, :destroy]
        resources :activities, only: [:index, :create, :show, :update, :destroy]
        resources :ppg_measures, only: [:index, :create, :show, :update, :destroy]
        resources :tags, only: [:index, :create, :show, :update, :destroy]
      end
    end
  end

end

backend/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action -> { rodauth.require_authentication }

  def index
  end

  def create_user
  end

  def search_user
    @users = User.search(params[:search])
    render "/dashboard/create_user"
  end

  def search_user_activities
    @users = User.search(params[:search])
    render "/dashboard/activity_user"
  end

  def view_activities
    @user = User.find(params[:id])
  end

  def get_activities
    @activities = Activity.where(user_id: params[:id]).order('start_d DESC')
  end

  def get_activities_sorted
    @activities = Activity.where(user_id: params[:id]).order('end_d DESC')
    @grouped_activities = @activities.group_by{ |t| t.end_d.to_date == DateTime.now.to_date }

    if @grouped_activities[false].present?
      #Create month wise groups of messages
      @day_wise_sorted_activities  = @grouped_activities[false].group_by{ |t| t.created_at.month}
    end
  end

  def activity_details
    @activity = Activity.find(params[:id_activity])
  end

  helper_method :get_activities, :get_activities_sorted, :activity_details, :search_user

end

backend/app/helpers/dashboard_helper.rb
module DashboardHelper

end

backend/app/views/dashboard/_form_create_user.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalLabel">Añadir usuario</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<%= form_with(model: user, url: users_path, method: :post, local: true, scope: :user) do |form| %>
<div class="modal-body">
  <div class="mb-3">
    <%= form.label 'Nombre', style: "col-form-label" %>
    <%= form.text_field :name, :class => 'form-control', :required => true %>
  </div>

  <div class="mb-3">
    <%= form.label 'Correo electrónico', style: "col-form-label" %>
    <%= form.email_field :email, :class => 'form-control', :required => true %>
  </div>

  <div class="mb-3">
    <%= form.label 'Contraseña', style: "col-form-label" %>
    <%= form.password_field :password_digest, :class => 'form-control', :required => true %>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
  <%= form.submit 'Añadir', :class => 'btn btn-success', :id => 'addUserModalButton' %>
</div>
<% end %>

backend/app/views/dashboard/_form_edit_user.html.erb
<% @usuario = usuario %>
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalLabel">Editar Usuario</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<%= form_with(model: @usuario, url: user_path(@usuario), method: "patch") do |form| %>
<div class="modal-body">
  <div class="mb-3">
    <%= form.label 'Nombre', style: "col-form-label" %>
    <%= form.text_field :name, :class => 'form-control', id: 'user'+@usuario.id.to_s+'name' %>
  </div>

  <div class="mb-3">
    <%= form.label 'Correo electrónico', style: "col-form-label" %>
    <%= form.email_field :email, :class => 'form-control', id: 'user'+@usuario.id.to_s+'username' %>
  </div>

  <div class="mb-3">
    <%= form.label 'Contraseña', style: "col-form-label" %>
    <div class="input-group mb-3">
      <%= form.text_field :password_digest, :class => 'form-control', :type =>'password', id: 'user'+@usuario.id.to_s+'password' %>
      <div class="input-group-append">
        <button class="btn btn-outline-danger" type="button" onclick="togglePassword('user<%= @usuario.id.to_s %>password')"><i data-feather="eye"></i></button>
      </div>
    </div>
  </div>
</div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
    <%= form.submit 'Editar', :class => 'btn btn-success' %>
  </div>
<% end %>

  <div class="modal-body" style="border-top: 1px solid #dee2e6">
    <%= form_with model: @usuario, url: user_private_api_keys_path do |f| %>
    <div class="mb-3">
      <h class="col-form-label">API Key</h>
      <%= f.text_field :private_api_key, disabled: true, :class => 'form-control' , id: 'user'+@usuario.id.to_s+'apiKEY'%>
      <%= f.hidden_field :id unless @usuario.id.nil?%>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-info" onclick="copy(<%= 'user'+@usuario.id.to_s+'apiKEY' %>)">Copiar</button>
    <%= f.submit "Cambiar Clave API", :class => 'btn btn-warning' %>
  </div>
<% end %>

backend/app/views/dashboard/activity_details.html.erb
<%= render "layouts/dashboard" %>
<%= stylesheet_link_tag 'create_user' %>

<% require "i18n" %>
<% @activity = activity_details %>
<% @activity.viewed = 1 %>
<% @activity.save %>
<% @user = User.find(params[:id]) %>
<% @tags = Tag.where(activity_id: @activity.id) %>
<% @stress = mid_process(@activity) %>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <div class="d-flex align-items-start ">
      <div class="btn-group me-2 btn-toolbar mb-2 mb-md-0">
        <%= link_to :back, :class => 'btn btn-sm btn-outline-secondary' do %>
          <i data-feather="arrow-left-circle" class="icon icon-show"></i>
        <% end %>
      </div>

      <h2>Actividad de <%= @activity.name %></h2>
      <% if @activity.end_d.nil? %>
        <div class="live-indicator">
          <figure class="live-indicator__circle"></figure>
          <span class="live-indicator__text">DIRECTO</span>
        </div>
      <% end %>
    </div>

    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group me-2">
        <a href="/activities/<%= @activity.id %>/export.csv" class="btn btn-sm btn-outline-secondary">Exportar</a>
        <a href="<%= @activity.id %>/reprocess" class="btn btn-sm btn-outline-secondary">Reprocesar</a>
      </div>
    </div>
  </div>
  <h4>Usuario: <%= @user.name %></h4>


  <div class="container-fluid">
    <div class="card text-center mb-3">
      <div class="card-header">
        Gráfico estrés
      </div>
      <div class="card-body">
        <h5 class="card-title">Gráfico nivel de estrés</h5>
        <canvas id="myChart" width="80vw" height="20vw"></canvas>
      </div>
    </div>
    <div class="card text-center mb-3">
      <div class="card-header">
        Etiquetado
      </div>
      <div class="card-body">
        <h5 class="card-title"></h5>
        <div class="table-responsive">
          <table class="table table-bordered table-striped align-middle table-sm">
            <thead>
            <tr>
              <th scope="col">Instante</th>
              <th scope="col">Estado</th>
              <th scope="col">Contexto</th>
              <th scope="col">Emoción</th>
              <th scope="col">Sentimiento</th>
            </tr>
            </thead>
            <tbody>
            <% @tags.each do |tag| %>
              <% @tag = JSON.parse(tag.tag) %>
              <tr>
                <td><%= tag.datetime.strftime("%H:%M") %></td>
                <td>
                  <div class="container">
                    <div class="row">
                        <div class="col-sm">
                          <figure>
                            <%= image_tag(asset_path("tags/#{I18n.transliterate(@tag["status"].downcase.gsub(" ", "_"))}.png"), :alt => @tag["status"], style: 'height:50px;width:autopx;') %>
                            <figcaption><%= @tag["status"] %></figcaption>
                          </figure>
                        </div>
                    </div>
                  </div>
                </td>
                <td>
                  <div class="container">
                    <div class="row">
                      <% @tag["context"].each do |tag| %>
                      <div class="col-sm">
                        <figure>
                          <%= image_tag(asset_path("tags/#{I18n.transliterate(tag.downcase.gsub(" ", "_"))}.png"), :alt => tag, style: 'height:50px;width:autopx;') %>
                          <figcaption><%= tag %></figcaption>
                        </figure>
                      </div>
                      <% end %>
                    </div>
                  </div>
                </td>
                <td>
                  <div class="container">
                    <div class="row">
                        <div class="col-sm">
                          <figure>
                            <%= image_tag(asset_path("tags/#{I18n.transliterate(@tag["emotions"].downcase.gsub(" ", "_"))}.png"), :alt => @tag["emotions"], style: 'height:35px;width:autopx;') %>
                            <figcaption><%= @tag["emotions"] %></figcaption>
                          </figure>
                        </div>
                    </div>
                  </div>
                </td>
                <td>
                  <div class="container">
                    <div class="row">
                        <div class="col-sm">
                          <figure>
                            <%= image_tag(asset_path("tags/#{I18n.transliterate(@tag["feelings"].downcase.gsub(" ", "_"))}.png"), :alt => @tag["feelings"], style: 'height:35px;width:autopx;') %>
                            <figcaption><%= @tag["feelings"] %></figcaption>
                          </figure>
                        </div>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>

        <p class="card-text">
        </p>
      </div>
    </div>
  </div>
</main>


<script>

    (function () {
        'use strict'

        // Graphs
        var ctx = document.getElementById('myChart').getContext("2d");
        // eslint-disable-next-line no-unused-vars
        var tranquilo = new Image(25,25);
        tranquilo.src = '<%= asset_url("tags/tranquilo") %>';
        var nervioso = new Image(25,25);
        nervioso.src = '<%= asset_url("tags/nervioso") %>';
        var yLabels = {
            '-2': 'No estresado', '0' : 'Estrés leve', '2' : 'Estresado'
        };
        const skipped = (ctx, value) => ctx.p0.skip || ctx.p1.skip ? value : undefined;
        const down = (ctx, value) => ctx.p0.parsed.y > ctx.p1.parsed.y ? value : undefined;
        const myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: <%= raw @stress.map { |stress| stress.datetime.strftime("%H:%M") } %>,
                datasets: [{
                    label: 'Nivel de estrés',
                    data: <%= raw @stress.map { |stress| if stress.level == -1 then Float::NAN else stress.level end } %>,
                    backgroundColor: 'transparent',
                    borderColor: '#f05f3a',
                    borderWidth: 2,
                    pointBackgroundColor: '#f05f3a',
                    segment: {
                        borderColor: ctx => skipped(ctx, 'rgb(0,0,0,0.2)') || down(ctx, 'rgb(192,75,75)'),
                        borderDash: ctx => skipped(ctx, [6, 6]),
                    },
                    spanGaps: true
                }]
            },
            options: {
                plugins: {
                    legend: false
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            callback: function(value, index, values) {
                                return yLabels[value];
                            }
                        }
                    }],
                    y: {
                        beginAtZero: false
                    }
                }
            }
        });
    })()
</script>

backend/app/views/dashboard/activity_user.html.erb
<%= render "layouts/dashboard" %>
<%= stylesheet_link_tag 'create_user' %>
<% if @users.nil? %>
  <% @users = User.all %>
<% end %>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Actividades</h1>
  </div>

  <h3>Seleccione un usuario</h3>
  <%= form_tag(dashboard_search_user_activity_path, method: :get) do %>

    <div class="input-group">
      <%= text_field_tag(:search, params[:search], :class => 'form-control rounded', :placeholder => 'Buscar usuario') %>
      <%= submit_tag ("BUSCAR"), :class => 'btn btn-outline-primary' %>
    </div>
  <% end %>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>
        </th>
        <th scope="col">Nombre</th>
        <th scope="col">Actividades</th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
          </td>
          <td><%= user.name %></td>
          <td>
            <%= link_to dashboard_view_activity_url(user), :class => 'btn btn-outline-primary' do%>
              <i data-feather="eye" class="icon icon-show"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</main>

backend/app/views/dashboard/create_user.html.erb
<%= render "layouts/dashboard" %>
<%= stylesheet_link_tag 'create_user.css' %>
<% if @users.nil? %>
<% @users = User.all %>
<% end %>


<script>
    function copy(inputname) {
        /* Get the text field */
        var copyText = document.getElementById(inputname);
        copyText.select();
        copyText.setSelectionRange(0, 99999); /* For mobile devices */
        /* Copy the text inside the text field */
        navigator.clipboard.writeText(copyText.value);

        /* Alert the copied text */
        alert("Copiada la clave API: " + copyText.value);
    }

    function togglePassword(inputname){
        var x = document.getElementById(inputname);
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    }

</script>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Usuarios registrados</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group me-2">
      <button id="addUserButton" class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#addUserModal">Añadir</button>
      </div>
    </div>
  </div>
  <%= form_tag(dashboard_search_user_path, method: :get) do %>

  <div class="input-group">
    <%= text_field_tag(:search, params[:search], :class => 'form-control rounded', :placeholder => 'Buscar usuario') %>
    <%= submit_tag ("BUSCAR"), :class => 'btn btn-outline-primary' %>
  </div>
  <% end %>

  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
      <tr>
        <th></th>
        <th scope="col">Nombre</th>
        <th scope="col">Opciones</th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td></td>
          <td><%= user.name %></td>
          <td>
            <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
              <div class="btn-group me-2" role="group" aria-label="First group">
                <button class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#editUserModal<%= user.id %>">
                  <i data-feather="edit" class="icon icon-show"></i>
                </button>
                <div id="editUserModal<%= user.id %>" class="modal fade">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <%= render "form_edit_user", usuario: user %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="btn-group me-2" role="group" aria-label="Second group">
                <%= button_to user, method: :delete, :class => 'btn btn-outline-danger', form: {data: {turbo_confirm: '¿Estás seguro de querer eliminar al usuario?'}} do%>
                  <i data-feather="trash-2" class="icon icon-show"></i>
                <% end %>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <div id="addUserModal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <%= render "form_create_user", user: @user %>
      </div>
    </div>
  </div>

</main>

backend/app/views/dashboard/index.html.erb
<%= render "layouts/dashboard" %>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Panel de control</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group me-2">
        <button type="button" class="btn btn-sm btn-outline-secondary">Compartir</button>
<!--        <button type="button" class="btn btn-sm btn-outline-secondary">Exportar</button>-->
        <a href="/activities/export.csv" class="btn btn-sm btn-outline-secondary">Exportar</a>

      </div>
      <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
        <span data-feather="calendar"></span>
        Esta semana
      </button>
    </div>
  </div>

  <canvas class="my-4 w-100 chartjs-render-monitor" id="myChart" width="1008" height="424" style="display: block; height: 212px; width: 504px;"></canvas>

  <h2>Registros</h2>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Header</th>
        <th scope="col">Header</th>
        <th scope="col">Header</th>
        <th scope="col">Header</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>1,001</td>
        <td>random</td>
        <td>data</td>
        <td>placeholder</td>
        <td>text</td>
      </tr>
      <tr>
        <td>1,002</td>
        <td>placeholder</td>
        <td>irrelevant</td>
        <td>visual</td>
        <td>layout</td>
      </tr>
      <tr>
        <td>1,003</td>
        <td>data</td>
        <td>rich</td>
        <td>dashboard</td>
        <td>tabular</td>
      </tr>
      </tbody>
    </table>
  </div>
</main>
</div>
</div>

<script>

    (function () {
        'use strict'

        // Graphs
        var ctx = document.getElementById('myChart')
        // eslint-disable-next-line no-unused-vars
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                datasets: [{
                    data: [
                        15339,
                        21345,
                        18483,
                        24003,
                        23489,
                        24092,
                        12034
                    ],
                    lineTension: 0,
                    backgroundColor: 'transparent',
                    borderColor: '#007bff',
                    borderWidth: 4,
                    pointBackgroundColor: '#007bff'
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: false
                        }
                    }]
                },
                legend: {
                    display: false
                }
            }
        })
    })()
</script>

backend/app/views/dashboard/view_activities.html.erb
<%= render "layouts/dashboard" %>
<%= stylesheet_link_tag 'create_user' %>
<% @activities = get_activities %>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group me-2">
        <%= link_to dashboard_activity_user_path, :class => 'btn btn-sm btn-outline-secondary' do %>
          <i data-feather="arrow-left-circle" class="icon icon-show"></i>
        <% end %>
      </div>
    </div>
    <h2>Actividades de <%= @user.name %> </h2>
  </div>

  <%- if @activities.size > 0 %>
    <div class="row align-items-start">
      <div class="col-md">
        <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h2>Viajar en bus</h2>
        </div>
        <div class="row row-cols-xxl-2 row-cols-1 g-2">
          <% @activities.select{|a| a.name == "Viajar en bus"}.each do |activity| %>
            <div class="col">
              <div class="card h-100">
                <% unless activity.viewed %>
              <span class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle">
              </span>
                <% end %>
                <div class="card-body">
                  <h5 class="card-title"><%= activity.name %></h5>
                  <p class="card-text"></p>
                  <div class="container">
                    <div class="row row-cols-auto g-2">
                      <div class="col">
                        <%= link_to dashboard_activity_details_url(id_activity: activity.id), :class => 'btn btn-primary g-2' do%>
                          Ver detalles
                        <% end %>
                      </div>
                      <%unless activity.end_d.nil? %>
                        <div class="col">
                            <%= button_to "Eliminar", activity, method: :delete, :class => 'btn btn-danger', form: {data: { turbo_confirm: "¿Estás seguro?" }} %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="card-footer">
                  <% unless activity.end_d.nil? %>
                    <small class="text-muted">Finalizó el
                      <b><%=  l activity.end_d, format: "%e de %B de %Y a las %k:%M:%S", locale: :'es-ES'  %></b>
                    </small>
                  <% else %>
                    <small class="text-muted">
                      <div class="live-indicator">
                        <figure class="live-indicator__circle"></figure>
                        <span class="live-indicator__text">DIRECTO</span>
                      </div>
                    </small>
                  <%  end %>
                </div>

              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md">
        <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h2>Viajar en metro </h2>
        </div>
        <div class="row row-cols-1 row-cols-xxl-2 g-2">
          <% @activities.select{|a| a.name == "Viajar en metro"}.each do |activity| %>
            <div class="col">
              <div class="card h-100">
                <% unless activity.viewed %>
              <span class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle">
              </span>
                <% end %>
                <div class="card-body">
                  <h5 class="card-title"><%= activity.name %></h5>
                  <p class="card-text"></p>
                  <div class="container">
                    <div class="row row-cols-auto g-2">
                      <div class="col">
                        <%= link_to dashboard_activity_details_url(id_activity: activity.id), :class => 'btn btn-primary g-2' do%>
                          Ver detalles
                        <% end %>
                      </div>
                      <%unless activity.end_d.nil? %>
                        <div class="col">
                          <%= button_to "Eliminar", activity, method: :delete, :class => 'btn btn-danger', form: {data: { turbo_confirm: "¿Estás seguro?" }} %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="card-footer">
                  <% unless activity.end_d.nil? %>
                    <small class="text-muted">Finalizó el
                      <b><%=  l activity.end_d, format: "%e de %B de %Y a las %k:%M:%S", locale: :'es-ES'  %></b>
                    </small>
                  <% else %>
                    <small class="text-muted">
                      <div class="live-indicator">
                        <figure class="live-indicator__circle"></figure>
                        <span class="live-indicator__text">DIRECTO</span>
                      </div>
                    </small>
                  <%  end %>
                </div>

              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md">
        <div class="d-flex flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h2>Viajar en tren </h2>
        </div>
        <div class="row row-cols-1 row-cols-xxl-2 g-2">
          <% @activities.select{|a| a.name == "Viajar en tren"}.each do |activity| %>
            <div class="col">
              <div class="card h-100">
                <% unless activity.viewed %>
              <span class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle">
              </span>
                <% end %>
                <div class="card-body">
                  <h5 class="card-title"><%= activity.name %></h5>
                  <p class="card-text"></p>
                  <div class="container">
                    <div class="row row-cols-auto g-2">
                      <div class="col">
                        <%= link_to dashboard_activity_details_url(id_activity: activity.id), :class => 'btn btn-primary g-2' do%>
                          Ver detalles
                        <% end %>
                      </div>
                      <%unless activity.end_d.nil? %>
                        <div class="col">
                          <%= button_to "Eliminar", activity, method: :delete, :class => 'btn btn-danger', form: {data: { turbo_confirm: "¿Estás seguro?" }} %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="card-footer">
                  <% unless activity.end_d.nil? %>
                    <small class="text-muted">Finalizó el
                      <b><%=  l activity.end_d, format: "%e de %B de %Y a las %k:%M:%S", locale: :'es-ES'  %></b>
                    </small>
                  <% else %>
                    <small class="text-muted">
                      <div class="live-indicator">
                        <figure class="live-indicator__circle"></figure>
                        <span class="live-indicator__text">DIRECTO</span>
                      </div>
                    </small>
                  <%  end %>
                </div>

              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

  <%- else %>
    <div class="card">
      <h5 class="card-header text-danger">Aviso</h5>
      <div class="card-body">
        <h5 class="card-title">El usuario aún no tiene ninguna medida</h5>
        <p class="card-text">Puede comenzar a medir en cualquier momento. Tan solo debe abrir la aplicación del reloj y comenzar la medición</p>
      </div>
    </div>
  <%- end %>

</main>